### ISSUE TITLE
don't install on atom 

### ISSUE THREAD

**Issue by thiagolucio** [praveenpuglia/ghar-syntax#1]
The apm install ghar-syntax have a problem.
Unable to download https://www.atom.io/api/packages/ghar-syntax/versions/2.1.0/tarball: 400 Bad Request Repository inaccessible

**Comment by praveenpuglia** [comment]
Looks like an apm issue. I raised an issue there and hoping to get some help.

**Comment by praveenpuglia** [comment]
@thiagolucio - the issue is resolved at `apm` end. Can you try installing again? Feel free to reopen the issue if it fails.
